66 friend contextmenu update
42LTeam/pong pull request #70
Opened 2023-08-17 19:49 UTC by werterhalimi

Hit me up pour le merge svp

2023-08-18 15:12 UTC, 0xlowell commented
ca bug dans l'ajout d'ami , et sinon tres cool de voir 

https://github.com/42LTeam/pong/assets/93135858/7ea113a9-5ebb-4da1-9518-6625fd9837b2

2023-08-18 15:30 UTC, 0xlowell requested changes
C K C

```Error: Prisma schema validation - (get-dmmf wasm)
Error code: P1012
error: Error parsing attribute "@default": Cannot set a default value on a relation field.
  -->  schema.prisma:66
   | 
65 |   creator    User?         @relation(fields: [creatorId], references: [id])
66 |   users      UserChannel[] @default([])
   | 
error: Error parsing attribute "@default": Cannot set a default value on a relation field.
  -->  schema.prisma:67
   | 
66 |   users      UserChannel[] @default([])
67 |   messages   Message[]     @default([])
   | 
Validation Error Count: 2
[Context: getDmmf]
Prisma CLI Version : 5.0.0```

2023-08-21 17:23 UTC, werterhalimi reviewed
fixed @0xlowell

2023-08-21 17:23 UTC, werterhalimi commented on back/prisma/schema.prisma
> +  users      UserChannel[] @default([])
```suggestion
  users      UserChannel[]
```

2023-08-21 17:23 UTC, werterhalimi commented on back/prisma/schema.prisma
> +  messages   Message[]     @default([])
```suggestion
  messages   Message[]   
```

2023-08-21 18:11 UTC, 8L312 approved these changes
Ça va être bien.. Ça va être très très bien même 🌴

2023-08-22 12:15 UTC, 0xlowell approved these changes
nice

2023-08-23 12:27 UTC, merged